### ISSUE TITLE
KVM Image not found

### ISSUE THREAD

**Issue by simcax** [k8s-proxmox/cluster-api-provider-proxmox#167]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
When the first VM is created it fails creation with not being able to find the KVM image, and fails with the following:

```log
 Logical volume "vm-109-cloudinit" created.
ide2: successfully created disk 'temphdd:vm-109-cloudinit,media=cdrom'
  Logical volume "vm-109-cloudinit" successfully removed
TASK ERROR: unable to create VM 109 - can't find file '/etc/cappx/images/c5eed826009c9f671bc5f7c9d5d63861aa2afe91aeff1c0d3a4cb5b28b2e35d6.ubuntu-22.04-server-cloudimg-amd64-disk-kvm.img'
```

Followed the [guide](https://github.com/k8s-proxmox/cluster-api-provider-proxmox)

My configuration:
## -- Controller settings -- ##
PROXMOX_URL: "https://proxmox.local.lan:8006/api2/json"
PROXMOX_PASSWORD: "...."

## -- Required workload cluster default settings -- ##
PROXMOX_SOURCENODE: "proxmox"
TEMPLATE_VMID: "9001"
ALLOWED_NODES: "[proxmox]"
VM_SSH_KEYS: "ssh-rsa ....."

## -- networking configuration-- ##
CONTROL_PLANE_ENDPOINT_IP: "172.10.10.110"
NODE_IP_RANGES: "[172.10.10.111-172.10.10.130]"
GATEWAY: "172.10.10.1"
IP_PREFIX: "32"
DNS_SERVERS: "[172.10.10.1]"
BRIDGE: "vmbr0"

## -- xl nodes-- ## 
BOOT_VOLUME_DEVICE: "scsi0"
BOOT_VOLUME_SIZE: "100"
NUM_SOCKETS: "1"
NUM_CORES: "4"
MEMORY_MIB: "8048"

EXP_CLUSTER_RESOURCE_SET: "true"

providers:
  - name: in-cluster
    url: https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster/releases/download/v0.1.0-alpha.3/ipam-components.yaml
    type: IPAMProvider

**What did you expect to happen:**
The VM to be created and configured

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-proxmox version: 0.3.4
- Proxmox VE version: 7.2.3
- Kubernetes version: (use `kubectl version`): 1.27.3
- OS (e.g. from `/etc/os-release`): Fedora 38

**Comment by JonasKop** [comment]
I am having the same issues:

**Setup management cluster:**
```bash
export EXP_CLUSTER_RESOURCE_SET=true
clusterctl init --infrastructure=proxmox:v0.3.4 --config https://raw.githubusercontent.com/k8s-proxmox/cluster-api-provider-proxmox/main/clusterctl.yaml
```

**Setup workload cluster:**
```bash
export CONTROLPLANE_HOST=1.2.3.10
export PROXMOX_URL=https://1.2.3.4:8006/api2/json
export PROXMOX_USER="some-user"
export PROXMOX_PASSWORD="some-password"

clusterctl generate cluster cappx-test \
    --control-plane-machine-count=1 \
    --worker-machine-count=1 \
    --infrastructure=proxmox:v0.3.4 \
    --config https://raw.githubusercontent.com/k8s-proxmox/cluster-api-provider-proxmox/main/clusterctl.yaml >cappx-test.yaml

# apply manifests
kubectl apply -f cappx-test.yaml
```

**Environment:**
- Cluster-api-provider-proxmox version: 0.3.4
- Proxmox VE version: 8.0.3
- Kubernetes version: (use kubectl version): v1.28.4
- OS (e.g. from /etc/os-release): Ubuntu 22.04

Gives loops of logs of:
```
I1218 12:49:08.051157       1 proxmoxmachine_controller.go:144] "Reconciling ProxmoxMachine" controller="proxmoxmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxMachine" ProxmoxMachine="default/cappx-test-md-0-tprzj" namespace="default" name="cappx-test-md-0-tprzj" reconcileID=17c9ea97-359f-4e21-b406-865d1a383861
I1218 12:49:08.054284       1 reconcile.go:24] "Reconciling instance" controller="proxmoxmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxMachine" ProxmoxMachine="default/cappx-test-md-0-tprzj" namespace="default" name="cappx-test-md-0-tprzj" reconcileID=17c9ea97-359f-4e21-b406-865d1a383861
I1218 12:49:08.054319       1 reconcile.go:105] "instance does not have providerID yet" controller="proxmoxmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxMachine" ProxmoxMachine="default/cappx-test-md-0-tprzj" namespace="default" name="cappx-test-md-0-tprzj" reconcileID=17c9ea97-359f-4e21-b406-865d1a383861
I1218 12:49:08.054334       1 scheduler.go:173] "Start Running Scheduler" Name="qemu-scheduler"
I1218 12:49:08.054366       1 reconcile.go:89] "instance wasn't found. new instance will be created" controller="proxmoxmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxMachine" ProxmoxMachine="default/cappx-test-md-0-tprzj" namespace="default" name="cappx-test-md-0-tprzj" reconcileID=17c9ea97-359f-4e21-b406-865d1a383861
I1218 12:49:08.054374       1 scheduler.go:196] "getting next qemu from scheduling queue" Name="qemu-scheduler"
I1218 12:49:08.054386       1 qemu.go:21] "Reconciling QEMU" controller="proxmoxmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxMachine" ProxmoxMachine="default/cappx-test-md-0-tprzj" namespace="default" name="cappx-test-md-0-tprzj" reconcileID=17c9ea97-359f-4e21-b406-865d1a383861
I1218 12:49:08.054404       1 qemu.go:58] "getting qemu from vmid" controller="proxmoxmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxMachine" ProxmoxMachine="default/cappx-test-md-0-tprzj" namespace="default" name="cappx-test-md-0-tprzj" reconcileID=17c9ea97-359f-4e21-b406-865d1a383861
I1218 12:49:08.071116       1 qemu.go:68] "creating qemu" controller="proxmoxmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxMachine" ProxmoxMachine="default/cappx-test-md-0-tprzj" namespace="default" name="cappx-test-md-0-tprzj" reconcileID=17c9ea97-359f-4e21-b406-865d1a383861
I1218 12:49:08.071150       1 storage.go:15] "ensuring storage is available" controller="proxmoxmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxMachine" ProxmoxMachine="default/cappx-test-md-0-tprzj" namespace="default" name="cappx-test-md-0-tprzj" reconcileID=17c9ea97-359f-4e21-b406-865d1a383861
I1218 12:49:08.071170       1 storage.go:40] "finding available storage" controller="proxmoxmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxMachine" ProxmoxMachine="default/cappx-test-md-0-tprzj" namespace="default" name="cappx-test-md-0-tprzj" reconcileID=17c9ea97-359f-4e21-b406-865d1a383861
I1218 12:49:08.073738       1 qemu.go:75] "making qemu spec" controller="proxmoxmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxMachine" ProxmoxMachine="default/cappx-test-md-0-tprzj" namespace="default" name="cappx-test-md-0-tprzj" reconcileID=17c9ea97-359f-4e21-b406-865d1a383861
I1218 12:49:08.073786       1 scheduler.go:261] "adding qemu to scheduler queue" Name="qemu-scheduler" qemu="cappx-test-md-0-tprzj"
I1218 12:49:08.073831       1 scheduler.go:203] "scheduling qemu" Name="qemu-scheduler" qemu="cappx-test-md-0-tprzj"
I1218 12:49:08.073855       1 scheduler.go:280] "finding proxmox node matching qemu" Name="qemu-scheduler" qemu="cappx-test-md-0-tprzj"
I1218 12:49:08.076318       1 scheduler.go:327] "filtering proxmox node" Name="qemu-scheduler" qemu="cappx-test-md-0-tprzj"
I1218 12:49:09.853455       1 scheduler.go:311] "finding proxmox vmid to be assigned to qemu" Name="qemu-scheduler" qemu="cappx-test-md-0-tprzj"
I1218 12:49:12.850983       1 scheduler.go:402] "no vmid key found. using nextid" Name="qemu-scheduler" qemu="cappx-test-md-0-tprzj"
I1218 12:49:14.884123       1 scheduler.go:196] "getting next qemu from scheduling queue" Name="qemu-scheduler" qemu="cappx-test-md-0-tprzj"
E1218 12:49:14.884277       1 scheduler.go:272] "failed to create qemu: map[]" err="unable to create VM 102 - can't find file '/etc/cappx/images/c5eed826009c9f671bc5f7c9d5d63861aa2afe91aeff1c0d3a4cb5b28b2e35d6.ubuntu-22.04-server-cloudimg-amd64-disk-kvm.img'" Name="qemu-scheduler" qemu="cappx-test-md-0-tprzj"
E1218 12:49:14.884428       1 qemu.go:81] "failed to create qemu instance" err="unable to create VM 102 - can't find file '/etc/cappx/images/c5eed826009c9f671bc5f7c9d5d63861aa2afe91aeff1c0d3a4cb5b28b2e35d6.ubuntu-22.04-server-cloudimg-amd64-disk-kvm.img'" controller="proxmoxmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxMachine" ProxmoxMachine="default/cappx-test-md-0-tprzj" namespace="default" name="cappx-test-md-0-tprzj" reconcileID=17c9ea97-359f-4e21-b406-865d1a383861
E1218 12:49:14.884539       1 qemu.go:42] "failed to create qemu" err="unable to create VM 102 - can't find file '/etc/cappx/images/c5eed826009c9f671bc5f7c9d5d63861aa2afe91aeff1c0d3a4cb5b28b2e35d6.ubuntu-22.04-server-cloudimg-amd64-disk-kvm.img'" controller="proxmoxmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxMachine" ProxmoxMachine="default/cappx-test-md-0-tprzj" namespace="default" name="cappx-test-md-0-tprzj" reconcileID=17c9ea97-359f-4e21-b406-865d1a383861
E1218 12:49:14.884632       1 reconcile.go:27] "failed to create/get instance" err="unable to create VM 102 - can't find file '/etc/cappx/images/c5eed826009c9f671bc5f7c9d5d63861aa2afe91aeff1c0d3a4cb5b28b2e35d6.ubuntu-22.04-server-cloudimg-amd64-disk-kvm.img'" controller="proxmoxmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxMachine" ProxmoxMachine="default/cappx-test-md-0-tprzj" namespace="default" name="cappx-test-md-0-tprzj" reconcileID=17c9ea97-359f-4e21-b406-865d1a383861
E1218 12:49:14.884730       1 proxmoxmachine_controller.go:160] "Reconcile error" err="unable to create VM 102 - can't find file '/etc/cappx/images/c5eed826009c9f671bc5f7c9d5d63861aa2afe91aeff1c0d3a4cb5b28b2e35d6.ubuntu-22.04-server-cloudimg-amd64-disk-kvm.img'" controller="proxmoxmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxMachine" ProxmoxMachine="default/cappx-test-md-0-tprzj" namespace="default" name="cappx-test-md-0-tprzj" reconcileID=17c9ea97-359f-4e21-b406-865d1a383861
E1218 12:49:14.893414       1 controller.go:324] "Reconciler error" err="unable to create VM 102 - can't find file '/etc/cappx/images/c5eed826009c9f671bc5f7c9d5d63861aa2afe91aeff1c0d3a4cb5b28b2e35d6.ubuntu-22.04-server-cloudimg-amd64-disk-kvm.img'" controller="proxmoxmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxMachine" ProxmoxMachine="default/cappx-test-md-0-tprzj" namespace="default" name="cappx-test-md-0-tprzj" reconcileID=17c9ea97-359f-4e21-b406-865d1a383861
```

**Comment by rhjensen79** [comment]
Got exactly the same.
Anybody found a workaround or a fix ?

**Comment by sp-yduck** [comment]
Hi, thank you all for bringing the issue up here ! 
I think I fixed the issue. please try v0.3.5. thanks again !

**Comment by simcax** [comment]
I tried it out, and right now VMs are being provisioned. I have some kinks to work out, gettting the right VM cloned etc. But it is definetely looking better :-)

**Comment by sp-yduck** [comment]
@simcax 
I think that's not an issue at all ? as you can see the event says `Node cappx-test-s8dc7 status is now: NodeHasNoDiskPressure` 
also network is not ready until you apply the CNI. it's expected.

**Comment by rhjensen79** [comment]
I'm still struggeling getting mine working.
v0.3.5 fixed the issue i had, but i still cannot deploy a full cluster.
I opened #179 around my issue, to keep it separate.

**Comment by simcax** [comment]
@sp-yduck 
Sorry my brain must not have worked that day :-) Thank you for pointing that out. I now get to a working state, with the CNI installed.
One curious thing though, is that I only get one controlplane node, despite setting 3. And nothing really happens as far as I can tell in the logs.

```
Name:         cluster05
Namespace:    default
Labels:       cluster.x-k8s.io/cluster-name=cluster05
Annotations:  <none>
API Version:  cluster.x-k8s.io/v1beta1
Kind:         Cluster
Metadata:
  Creation Timestamp:  2024-04-27T07:15:13Z
  Finalizers:
    cluster.cluster.x-k8s.io
  Generation:        1
  Resource Version:  449727
  UID:               7053040a-286a-4553-9b13-17d302290b04
Spec:
  Control Plane Endpoint:
    Host:  172.20.20.101
    Port:  6443
  Control Plane Ref:
    API Version:  controlplane.cluster.x-k8s.io/v1beta1
    Kind:         KubeadmControlPlane
    Name:         cluster05
    Namespace:    default
  Infrastructure Ref:
    API Version:  infrastructure.cluster.x-k8s.io/v1beta1
    Kind:         ProxmoxCluster
    Name:         cluster05
    Namespace:    default
Status:
  Conditions:
    Last Transition Time:  2024-04-27T07:15:21Z
    Message:               Scaling up control plane to 3 replicas (actual 1)
    Reason:                ScalingUp
    Severity:              Warning
    Status:                False
    Type:                  Ready
    Last Transition Time:  2024-04-27T07:18:32Z
    Status:                True
    Type:                  ControlPlaneInitialized
    Last Transition Time:  2024-04-27T07:15:21Z
    Message:               Scaling up control plane to 3 replicas (actual 1)
    Reason:                ScalingUp
    Severity:              Warning
    Status:                False
    Type:                  ControlPlaneReady
    Last Transition Time:  2024-04-27T07:15:14Z
    Status:                True
    Type:                  InfrastructureReady
  Control Plane Ready:     true
  Infrastructure Ready:    true
  Observed Generation:     1
  Phase:                   Provisioned
Events:
  Type    Reason               Age                From                Message
  ----    ------               ----               ----                -------
  Normal  Provisioning         31m (x2 over 31m)  cluster-controller  Cluster cluster05 is Provisioning
  Normal  InfrastructureReady  31m (x2 over 31m)  cluster-controller  Cluster cluster05 InfrastructureReady is now true
  Normal  Provisioned          31m (x2 over 31m)  cluster-controller  Cluster cluster05 is Provisioned
  Normal  ControlPlaneReady    25m                cluster-controller  Cluster cluster05 ControlPlaneReady is now true
```
To me it looks like the machine for the first controlplane is not discovered after the fact:

```
I0427 07:51:21.053477       1 recorder.go:104] "Waiting for control plane to pass preflight checks to continue reconciliation: Machine cluster05-r4mgj does not have a corresponding Node yet (Machine.status.nod │
│ eRef not set)" logger="events" type="Warning" object={"kind":"KubeadmControlPlane","namespace":"default","name":"cluster05","uid":"21c04db6-7552-4d18-9c00-6bc097fd7336","apiVersion":"controlplane.cluster.x-k8s │
│ .io/v1beta1","resourceVersion":"452062"} reason="ControlPlaneUnhealthy"
```

Despite that I can see the machine in proxmox, and connect to the cluster and install the CNI and such.

**Comment by rhjensen79** [comment]
Give issue #179 and see if a restart of the pod, triggers the deployment. 
It sounds like like some of the same things i'm seeing.

**Comment by simcax** [comment]
@rhjensen79  - indeed it is the same thing. I will continue in #179
